name: Build on Multiple OS and Architectures

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]  # Add arm64 for Apple Silicon support
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'  # or your desired Java version
          cache: 'maven'

      - name: Test,Compile and Build
        run: make build-all

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: target/shaded/*  # Adjust the file path to your release artifacts
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


